[package]
name = "basic"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
# Origin can be depended on just like any other crate.
origin = { path = "../.." }

# This is just an example crate, and not part of the origin workspace.
[workspace]
